server:
  host: "localhost"
  listen_port: "8080"

resources: 
  - name: Server1 
    endpoint: /server1 
    destinationUrl: "http://localhost:9001"
  - name: Server2 
    endpoint: /server2 
    destinationUrl: "http://localhost:9002"
  - name: Server3 
    endpoint: /server3 
    destinationUrl: "http://localhost:9003"
  - name: Server4 
    endpoint: /server4 
    destinationUrl: "http://localhost:9004"
  - name: Server5 
    endpoint: /server5 
    destinationUrl: "http://localhost:9005"